faiss.settings:
  type: config_object
  label: 'FAISS Settings'
  mapping:
    index_path:
      type: string
      label: 'Index Storage Path'
      required: true
    index_type:
      type: string
      label: 'Index Type'
      required: false
    distance_metric:
      type: string
      label: 'Distance Metric'
      required: false
    nlist:
      type: integer
      label: 'Number of Lists (for IVF indexes)'
      required: false 